name: stock
on: workflow_dispatch
jobs:
  gradle_build:
    name: Build by gradle
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
          architecture: x64
      - run: java --version
      - run: gradle -v
      - run: gradle build
      - run: ls
      - run: ls build/libs
